### ISSUE TITLE
Inline code blocks are wrapped in tables before plain text

### ISSUE THREAD

**Issue by mnquintana** [primer/markdown#47]
See https://github.com/atom/toggle-quotes/blob/mq-readme/README.md#configuration

`toggle-quotes.quoteCharacters` under Configuration Key Path is wrapping, but this is quite strange since there is enough leeway for the text under Description to wrap instead, if that makes sense.

**Comment by djch** [comment]
Definitely makes sense.

Adding `white-space: nowrap` seems to fix it, but I guess that begs the question, "should `nowrap` be scoped just to code inside tables or all code elements?".

It *does* seem a little awkward to be wrapping inline code snippets in general. I guess we'll leave that up to GitHub :octocat: .

**Comment by jonrohan** [comment]
The wrapping of inline `<code>` snippets is expected behavior. We don't wrap code blocks with triple ticks.

It doesn't seem this is happening on the toggle-quotes page anymore https://github.com/atom/toggle-quotes/blob/2c5a9dfabd17c90cca438bf42e4e6a758c241aaf/README.md#configuration So i'm closing this issue.

**Comment by mnquintana** [comment]
@jonrohan It's still wrapping for me on Chrome 46: 
<img width="256" alt="toggle-quotes_readme_md_at_2c5a9dfabd17c90cca438bf42e4e6a758c241aaf_ _atom_toggle-quotes" src="https://cloud.githubusercontent.com/assets/823545/10916786/30bdd390-822b-11e5-8db1-96f72203e352.png">

That makes sense, but I do get the same wrapping with triple ticks (if the code block is only one line, like it is here)
